%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-thunder-line-follower-pmr3100
Version:        0.1.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS thunder_line_follower_pmr3100 package

License:        MIT
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo
Requires:       pygame-devel
Requires:       ros-noetic-controller-manager
Requires:       ros-noetic-gazebo-plugins
Requires:       ros-noetic-gazebo-ros
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-joint-state-publisher
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-roslaunch
Requires:       ros-noetic-rospy
Requires:       ros-noetic-velocity-controllers
Requires:       ros-noetic-xacro
BuildRequires:  gazebo
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-gazebo-plugins
BuildRequires:  ros-noetic-gazebo-ros
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-joint-state-publisher
BuildRequires:  ros-noetic-robot-state-publisher
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rospy
BuildRequires:  ros-noetic-velocity-controllers
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Simulation environment for a line follower development Created for the
discipline PMR3100 - Intro to Mechatronics from Poli-USP

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Jun 24 2021 ThundeRatz <comp@thunderatz.org> - 0.1.1-1
- Autogenerated by Bloom

